### ISSUE TITLE
Add new tool?

### ISSUE THREAD

**Issue by ciltocruz** [maximal/gitlab-code-quality#2]
Hello, thanks for this project.

What options are there to add Easy Code Standard ([ecs](https://github.com/easy-coding-standard/easy-coding-standard)) as a tool?

Thanks!

**Comment by maximal** [comment]
Hi there! I’ll investigate it and hopefully add in the observable future.

**Comment by ciltocruz** [comment]
Hello. Thank you. I've tried to do it myself but I've been unable to do it because I haven't been able to adapt it to the Gitlab format that gives ECS. :(

I hope it's not complicated for you. 

Thank you so much! 😜

**Comment by maximal** [comment]
@ciltocruz, can you try the latest release (v1.5)?

Unfortunately, I cannot run ECS checks in this generator on my production environments at the moment, but on my test projects these checks currently run just fine.

Also, note that ECS provides almost no information about specific line numbers and columns inside of the checked files, so, it can be an issue in real applications (showing widgets in GitLab, for instance).

**Comment by ciltocruz** [comment]
hahaha, it can't be! I hadn't seen this comment! I came to this repo to say that I was just doing tests with my gitlab pipeline and suddenly I saw ECS and I was blown away. hahaha

The report is coming out as expected!

But there are some things to improve. Yes, I agree with you that the ECS result is quite bad. Just the Diffs........

1. ¿ECS o ESC?
![image](https://github.com/maximal/gitlab-code-quality/assets/19903919/25c183f7-9d31-4a24-a8ec-591e267f01a8)

2. I have to see if I've made a mistake with something in the configuration because psalm works fine but ECS doesn't. The file path does not have the correct path.

**Comment by maximal** [comment]
@ciltocruz

1. My bad :-)

2. Send me, please: Psalm’s path, ECS’ path, real path, path relative to the project’s root (and relative to `composer.json` if they are different).

**Comment by ciltocruz** [comment]
1. I opened a MR #3

**Comment by ciltocruz** [comment]
> @ciltocruz
> 
> 1. My bad :-)
> 2. Send me, please: Psalm’s path, ECS’ path, real path, path relative to the project’s root (and relative to `composer.json` if they are different).

2.

Project path: /home/ciltocruz/project/
Psalm path: /home/ciltocruz/project/sources/vendor/bin/psalm
Psalm config: /home/ciltocruz/project/sources/psalm.xml
ECS path:  /home/ciltocruz/project/sources/vendor/bin/ecs
ECS config: /home/ciltocruz/project/sources/ecs.php
composer: /home/ciltocruz/project/sources/composer.json

For example:
Files: "api/Application/Service/BookingService.php"

Should be:
Files: "sources/api/Application/Service/BookingService.php"

I always execute from my root path:
`/home/ciltocruz/project/`
Like this (inside `/home/ciltocruz/project/`):
`./sources/vendor/bin/ecs --config=sources/ecs.php check --output-format json`

**Comment by maximal** [comment]
@ciltocruz, ah, I see. Quite unusual setup! I’l fix it. Thanks for the investigation.

**Comment by ciltocruz** [comment]
hahaha,... I know. It's a little weird.

Let's say that my project has the `sources` folder, which is where the entire project is, but in the root there are auxiliary folders that were created when the project was started, such as md files for documentation, sql files, tests... In short, the repo has to be able to access gitlab.com/user/project/SOURCES/{file} hahahahaha

Sorry for making it difficult and thank you very much for this work.

Something needs to be done with ECS, so that they are clearer in their "mistakes"... using `diff` seems pretty bad to me but neither you nor I can do anything...

**Comment by maximal** [comment]
@ciltocruz, at least I parse the first line number (of every detected issue) from the provided diffs. Better than nothing.

**Comment by ciltocruz** [comment]
Yes!

**Comment by ciltocruz** [comment]
hahaha 😆😆😆😆😂😂😂😂
You have to merge with this:
https://github.com/VantaFinance/GitlabRector

**Comment by maximal** [comment]
Closing this as the new tool is added. Moved path-related problem to the new issue: #5.
