### ISSUE TITLE
Non-zero exit code when issues are found

### ISSUE THREAD

**Issue by rezsk** [maximal/gitlab-code-quality#4]
Is there any way to set the script to return non-zero code when there are issues with the code?
Right now even when there are issues, it exits with 0 and the pipeline succeeds normally.
I think there should be an option to configure this behavior.

**Comment by maximal** [comment]
Hi, @rezsk!

Now I return non-zero exit code only if critical errors are found: in PHP case those are, for example, syntax parsing errors.

I think I can add some kind of `--strict` flag to return non-zero if ANY of issues found.

**Comment by maximal** [comment]
@rezsk, you can use the latest release with the strict mode added:

https://github.com/maximal/gitlab-code-quality/releases/tag/v1.6
